typography_spectrum: 0.3255319
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b6b6b6'
    - '#717171'
    - '#313131'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8766388
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: David McAllister
  email: kiddfunk@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4ab3cce9-b70c-4ca4-8d27-ea05180bfb19.jpg
name: 'KiddFunk '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: KF Web Site
description: '#gotstobefunky'
purpose: []
